name: Feature Branch Workflow

on:
  workflow_dispatch:
    branches: [ feature/* ]

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/easey-emissions-api
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          path: devops
      - name: Build
        run: ls -lhart; sudo devops/scripts/build.sh
      - name: Check Licenses
        run: sudo devops/scripts/validate-licenses.sh
     
